config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	root 'welcome#index'
  	devise_for :users, controllers: { sessions: 'sessions', :registrations => 'registrations', :omniauth_callbacks => 'omniauth_callbacks' }  do
    	get 'logout' => 'devise/sessions#destroy'
	end
	match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


	get '/about' => 'misc#about'
	get '/why' => 'misc#why'
	get '/terms-condition' => 'misc#terms-condition'
	get '/pledge-now' => 'misc#pledge_now'
	get '/how' => 'misc#how'
	match '/feedback' => 'misc#feedback', via: [:get, :post]
	get '/disclaimer' => 'misc#disclaimer'
	get '/terms-and-conditions' => 'misc#terms_and_conditions'

	get '/api/find_children' => 'api#find_children'
	post '/payment' => 'api#payment'
	post '/valid-refid' => 'api#valid_refid'
	post '/shared-contributions/:id/' => 'api#payment'

	get '/update-profile' => 'users#update_profile'

	post '/payu/ok' => 'payu#ok'
	post '/payu/error' => 'payu#error'
	post '/payu/report' => 'payu#report'

	post '/profile-update' => 'users#profile_update'
	get '/member-associate' => 'users#member_associate'
	match '/save-profile' => 'users#save_profile', via: [:patch, :post]
	post '/save-child' => 'users#save_child'

	get '/buddy-referrals' => 'users#buddy_referrals'
	get '/registered-children' => 'users#registered_children'
	post '/invite-referral' => 'users#invite_referral'
	match '/change-password' => 'users#change_password', via: [:get, :post]

	post 'payment/checkout'
  	get 'payment/:id/cancle' => 'payment#cancle'
	get 'payment/:id/success' => 'payment#success'
	post 'payment/:id/ipn_notify' => 'payment#ipn_notify'

end

app/views/shared/_flash.html.erb
<%= content_tag( "div", class: "flash_message" ) do %>
	<% if flash[level].present? %>
		<div class="<%= flash_class(level) %> pd10-LR pd5-TB" style="padding:5px;margin-bottom:10px;position:static;<%= 'background-color:#fcf8e3;color:#8a6d3b;' if flash_class(level) == 'info_msg' %>">
		<% if level.to_s == "success" %>
	    	<span class="f-green fs12"><%= flash[level] %></span>
		<% elsif level.to_s == "error" %>
	    	<span class="f-red fs12"><%= flash[level] %></span>
		<% else %>
	    	<span class="fs12"><%= flash[level] %></span>
		<% end %>
	  	</div>
	<% end %>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_message">
	<% if flash[level].present? %>
		<div class="<%= flash_class(level) %> pd10-LR pd5-TB" style="margin-bottom:10px;position:static;<%= 'background-color:#fcf8e3;color:#8a6d3b;' if flash_class(level) == 'info_msg' %>">
		<% if level.to_s == "success" %>
	    	<span class="f-green fs12"><%= flash[level] %></span>
		<% elsif level.to_s == "error" %>
	    	<span class="f-red fs12"><%= flash[level] %></span>
		<% else %>
	    	<span class="fs12"><%= flash[level] %></span>
		<% end %>
	  	</div>
	<% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="container">
		<div class="pleft"> <a href='/terms-and-conditions'>Terms & Conditions </a> <a href='/disclaimer'>Disclaimer</a> <a href='/feedback'>Feedback</a> </div>
		<div class="pright">&copy; MULCHCARE 2014</div>
	</div>
</footer>

app/views/shared/_header.html.erb
	<div class="toph1">
	  	<div class="container">
			<div class="logo pleft">
				<a><img src="/assets/logo.png" alt="Home"></a>
			</div>
			<div class="pright" style="margin: 10px 120px auto auto;">
        		<ul class="nav navbar-nav navT">
					<% if user_signed_in? %>
	    				<li class="dropdown"><a href='#' data-toggle="dropdown"> Hi, <%= current_user.alias_name %> <%= image_tag current_user.avatar.url, size: '20x20' %></a>
					        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
					        	<li><%= link_to "Refer Buddy", buddy_referrals_path %></li>
					        	<li><%= link_to "Registered Children", registered_children_path %></li>
					        	<li><%= link_to "Update Profile", update_profile_path %></li>
					        	<li><%= link_to "Change Password", change_password_path %></li>
					        	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
					        </ul>
				        </li>
	        		<% else %>
	        			<li><a href='/users/sign_in'>Sign In </a></li>
	    				<li class="active"><a href="/users/sign_up">Free Enrollment </a></li>
	        		<% end %>
			    </ul>
			</div>
		</div>
	</div>
	<div class="navbar thmcolor" role="navigation">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>
	    <div class="collapse navbar-collapse">
	      <ul class="nav navbar-nav navM">
	        <li class="active"><a href="/">Home</a></li>
	        <li><a href="/about">About MULCH</a></li>
	        <li><a href="/why">Why MULCH</a></li>
	        <li><a href="/how">How It Works</a></li>
	        <%= "<li class='active'><a href='/pledge-now'>Pledge Now</a></li>".html_safe if user_signed_in? %>
	        <li><a href="/member-associate">Become a Member/Associate</a></li>	        
	      </ul>
	    </div><!-- /.nav-collapse -->
	  </div><!-- /.container -->
	</div><!-- /.navbar -->

app/views/shared/_update_profile.html.erb
  <%= render partial: '/shared/flash_messages', collection: [:notice, :alert, :success, :error], as: :level %>
  
  <h1 class="pcenter"> <%= title %> </h1> 

      <span class='flash_messages'></span>

      <%= form_for @user, :url => save_profile_path, html: { onsubmit: "if($('.edit_user').valid() && ssn_unmasking()){show_loader('.flash_messages', '.loader')}" }, method: :post do |f| %>
        
        <!-- <input name="authenticity_token" type="hidden" value="<%#= form_authenticity_token %>"> -->

    <div class="c1 col-xs-12">
	    <div class="hd1">
		    <i class='fa fa-bars'></i> Personal Information
		</div>
		<div class="content">
            <%= f.hidden_field :id, value: @user.id %>
            <%= content_tag( "div", class: "form-group" ) do %>
              <%= f.label "Full Name *", class: "col-sm-2 control-label", for: 'user_first_nm' %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                <%= f.text_field :first_nm, autofocus: true, class: "txtOnlyAlpha form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'First Name *', required: true %>
              <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                    <%= f.text_field :last_nm, class: "txtOnlyAlpha form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'Last Name *', required: true %>
                <% end %>
            <% end %>

            <% if register_as_child? %>
    
              <%= content_tag( "div", class: "form-group" ) do %>
                <%= f.label "DOB", class: 'col-sm-2 control-label', for: 'user_dob' %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>        
                      <%= f.text_field :dob, value: (@user.dob.nil? ? '' : @user.dob.strftime('%m/%d/%Y')), class: "datepicker form-control", placeholder: "MM/DD/YYYY", onchange: 'age_calculate()', readonly: true %>
                <% end %>
              <% end %>

              <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                  <%= f.text_field :role, class: "form-control", placeholder: "Role", disabled: true %>
                <% end %>
              <% end %>

              <%= content_tag( "div", class: "form-group user_role", style: 'display:none;' ) do %>
                <%= f.label " ", class: 'col-sm-2 control-label', for: 'user_email' %>
                <%= content_tag( "div", class: "col-sm-10" ) do %>
                  <%= f.label "Student has to utilize the amount within 7 years, else the amount would be moved to Non-Profit Organization account", class: "form-control info" %>
                <% end %>
              <% end %>

            <% else %>

                <%= content_tag( "div", class: "form-group" ) do %>
                    <%= f.label "DOB *", class: 'col-sm-2 control-label', for: 'user_dob' %>
                    <%= content_tag( "div", class: "col-sm-10" ) do %>
                        <%= f.text_field :dob, value: (@user.dob.nil? ? '' : @user.dob.strftime('%m/%d/%Y')), class: "datepicker form-control", placeholder: "MM/DD/YYYY", readonly: true %>
                    <% end %>
                <% end %>

                <%= content_tag( "div", class: "form-group" ) do %>
                    <%= f.label "Email", class: 'col-sm-2 control-label', for: 'user_email' %>
                    <%= content_tag( "div", class: "col-sm-10" ) do %>
                        <%= f.email_field :email, autocomplete: "off", class: "form-control", placeholder: "Email", disabled: true %>
                    <% end %>
                <% end %>
      
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= f.label "Gender", class: 'col-sm-2 control-label', for: 'user_gender' %>
                <%= content_tag( "div", class: "col-sm-10 radio fnt18", style: "margin-top: 5px;" ) do %>
                  <input type="radio" name="user[gender]" id="gender_male" class="user_gender css-radio" value="male" <%= "checked" if @user[:gender]=="male" %>>
                  <label class="col-sm-2 css-label-radio" for="gender_male">Male</label>
                  <input type="radio" name="user[gender]" id="gender_female" class="user_gender css-radio" value="female" <%= "checked" if @user[:gender]=="female" %>>
                  <label class="col-sm-2 css-label-radio" for="gender_female">Female</label>
                <% end %>
            <% end %>
        </div>
    </div>
        <% if register_as_child? %>
          <%= content_tag( "div", class: "form-group" ) do %>
            <%= f.label "Phone", class: 'col-sm-2 control-label', for: 'user_phone' %>
            <%= content_tag( "div", class: "col-sm-5" ) do %>
              <%= f.text_field :phone, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Home Phone" %>
            <% end %>
          <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <%= f.text_field :mobile, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Mobile *" %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= f.label "Profile Picture *", class: 'col-sm-2 control-label', for: 'user_profile' %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <div class="browse col-sm-8" onclick="image_via_file(this);"> <i class='fa fa-image'></i> &nbsp &nbsp Browse</div>
          <img src="<%= @user.avatar.url %>" id="img-preview" class="pull-right" width="50px" height="50px">
          <%= f.file_field :avatar, class: "choose-file form-control", pattern: ".jpg, .png" %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <%= f.hidden_field :ssn, value: @user.ssn %>
          <input class="form-control txtOnlyNumber valid" id="ssn" placeholder="SSN - Social Security No" data-value='<%= @user.ssn %>' type="text" aria-invalid="false">
        <% end %>
      <% end %>

      <%= f.fields_for :guardians do |ff| %>
        <%= render '/shared/update_profile_guardians', ff: ff, index: @user.guardians.index(ff.object) if @user.guardians.index(ff.object) <= 1 %>
      <% end %>
    <% end %>

    <% unless register_as_child? %>
    <div class="c1 col-xs-12">
	    <div class="hd1">
		    <i class='fa fa-bars'></i> Contact
		</div>
		<div class="content">
         
      
            <%= content_tag( "div", class: "form-group" ) do %>
                <%= f.label "Home Address", class: 'col-sm-2 control-label', for: 'user_appt_no' %>
                <%= content_tag( "div", class: "col-sm-3" ) do %>
                  <%= f.text_field :appt_no, class: "form-control", placeholder: "Appt No" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-4" ) do %>
                    <%= f.text_field :st_no, class: "form-control", placeholder: "Street No" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-3" ) do %>
                    <%= f.text_field :city, class: "form-control", placeholder: "City" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= f.label "Phone", class: 'col-sm-2 control-label', for: 'user_phone' %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                    <%= f.text_field :phone, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Home Phone" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                    <%= f.text_field :mobile, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Mobile *" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= f.label "Profile Picture", class: 'col-sm-2 control-label', for: 'user_profile' %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                  <div class="browse col-sm-8" onclick="image_via_file(this);"> <i class='fa fa-image'></i> &nbsp &nbsp Browse</div>
                  <img src="<%= @user.avatar.url %>" id="img-preview" class="pull-right" width="50px" height="50px">
                  <%= f.file_field :avatar, class: "choose-file form-control", pattern: ".jpg, .png" %>
                <% end %>
            <% end %>

            <%= content_tag( "div", class: "form-group" ) do %>
                <%= content_tag( "div", class: "col-sm-5" ) do %>
                    <%= f.hidden_field :ssn, value: @user.ssn %>
                    <input class="form-control txtOnlyNumber valid" id="ssn" placeholder="SSN - Social Security No" data-value='<%= @user.ssn %>' type="text" aria-invalid="false">
                <% end %>
            <% end %>
        <% end %>

        <% if become_member_associate? %>
          <%= content_tag( "div", class: "form-group" ) do %>
            <%= "&nbsp".html_safe %>
          <% end %>
          <%= content_tag( "div", class: "form-group" ) do %>
              <%= f.label "Select type", class: 'col-sm-2 control-label', for: 'user_role' %>
              <%= content_tag( "div", class: "col-sm-10 radio fnt18", style: "margin-top: 5px;" ) do %>
                <input type="radio" name="user[role]" id="role_member" class="user_role css-radio" value="member" <%= "checked" if @user[:role]=="member" %>>
                <label class="col-sm-2 css-label-radio" for="role_member">Member</label>
                <input type="radio" name="user[role]" id="role_associate" class="user_role css-radio" value="associate" <%= "checked" if @user[:role]=="associate" %>>
                <label class="col-sm-2 css-label-radio" for="role_associate">Associate</label>
              <% end %>
          <% end %>
        <% end %>
        </div>
    </div>
        <%= content_tag( "div", class: "form-group" ) do %>
            <%= link_to "<i class='fa fa-save'></i> Update".html_safe, "javascript:$('.edit_user').submit()", class: 'col-sm-5 btn btn-primary pull-left' %>
            <div class="loader col-sm-2" style="display:none;"><img src="/assets/ajax-loader.gif"> Please wait..</div>
            <%= link_to "Skip >>", '/pledge-now', class: 'col-sm-5 btn btn-primary pull-right' unless become_member_associate? %>
        <% end %>

      <% end %>

<script>
  $(document).ready(function(){age_calculate});
</script>

app/views/shared/_update_profile_guardians.html.erb
<% if index == 0 %>
  <div class="c1 col-xs-12">
    <div class="hd1">
      <i class='fa fa-bars'></i> Mother/Guardian Detail
    </div>  
    <div class="content">
      <%= ff.hidden_field :id, value: @user.guardians[index].id %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Name", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <% if current_user.gender == 'female' %>
            <%= ff.text_field :first_nm, value: current_user.first_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'First Name' %>
          <% else %>
            <%= ff.text_field :first_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'First Name' %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <% if current_user.gender == 'female' %>
            <%= ff.text_field :last_nm, value: current_user.last_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'Last Name' %>
          <% else %>
            <%= ff.text_field :last_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'Last Name' %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Email", class: 'col-sm-2 control-label', for: 'user_email' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <% if current_user.gender == 'female' %>
            <%= email_field_tag :email, "#{current_user.email}", autocomplete: "off", class: "form-control", placeholder: "Email", disabled: true %>
          <% else %>
            <%= email_field_tag :email, "", autocomplete: "off", class: "form-control", placeholder: "Email" %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "DOB", class: 'col-sm-2 control-label pull-left', for: '' %>
        <%= content_tag( "div", class: "col-sm-10 pull-right" ) do %>
          <% if current_user.gender == 'female' %>
            <%= ff.text_field :dob, value: (current_user.dob.nil? ? '' : current_user.dob.strftime('%m/%d/%Y')), class: "datepicker form-control", placeholder: "MM/DD/YYYY", readonly: true %>
          <% else %>
            <%= ff.text_field :dob, class: "datepicker form-control", placeholder: "MM/DD/YYYY", readonly: true %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Address", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <%= ff.text_field :address, class: "form-control", placeholder: "Address" %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Phone", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <% if current_user.gender == 'female' %>
            <%= ff.text_field :phone, value: current_user.phone, class: "txtOnlyNumber form-control", placeholder: "Phone" %>
          <% else %>
            <%= ff.text_field :phone, class: "txtOnlyNumber form-control", placeholder: "Phone" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="c1 col-xs-12">
    <div class="hd1">
      <i class='fa fa-bars'></i> Father/Guardian Detail
    </div>
    <div class="content">
      <%= ff.hidden_field :id, value: @user.guardians[index].id %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Name", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :first_nm, value: current_user.first_nm, class: "form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'First Name' %>
          <% else %>
            <%= ff.text_field :first_nm, class: "form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'First Name' %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-5" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :last_nm, value: current_user.last_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'Last Name' %>
          <% else %>
            <%= ff.text_field :last_nm, class: "form-control", autocomplete: "off", pattern: '[a-zA-Z]{3,20}', oninput: 'check_names(this)', placeholder: 'Last Name' %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Email", class: 'col-sm-2 control-label', for: 'user_email' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <% if current_user.gender == 'male' %>
            <%= email_field_tag :email, "#{current_user.email}", autocomplete: "off", class: "form-control", placeholder: "Email", disabled: true %>
          <% else %>
            <%= email_field_tag :email, "", autocomplete: "off", class: "form-control", placeholder: "Email" %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "DOB", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :dob, value: (current_user.dob.nil? ? '' : current_user.dob.strftime('%m/%d/%Y')),class: "datepicker form-control", placeholder: "MM/DD/YYYY", readonly: true %>
          <% else %>
            <%= ff.text_field :dob, class: "datepicker form-control", placeholder: "MM/DD/YYYY", readonly: true %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Address", class: 'col-sm-2 control-label', for: 'user_appt_no' %>
        <%= content_tag( "div", class: "col-sm-3" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :appt_no, value: current_user.appt_no, class: "form-control", placeholder: "Appt No" %>
          <% else %>
            <%= ff.text_field :appt_no, class: "form-control", placeholder: "Appt No" %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-4" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :st_no, value: current_user.st_no, class: "form-control", placeholder: "Street No" %>
          <% else %>
            <%= ff.text_field :st_no, class: "form-control", placeholder: "Street No" %>
          <% end %>
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= content_tag( "div", class: "col-sm-3" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :city, value: current_user.city, class: "form-control", placeholder: "City" %>
          <% else %>
            <%= ff.text_field :city, class: "form-control", placeholder: "City" %>
          <% end %>        
        <% end %>
      <% end %>

      <%= content_tag( "div", class: "form-group" ) do %>
        <%= ff.label "Phone", class: 'col-sm-2 control-label', for: '' %>
        <%= content_tag( "div", class: "col-sm-10" ) do %>
          <% if current_user.gender == 'male' %>
            <%= ff.text_field :phone, value: current_user.phone, class: "txtOnlyNumber form-control", placeholder: "Phone" %>
          <% else %>
            <%= ff.text_field :phone, class: "txtOnlyNumber form-control", placeholder: "Phone" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>