config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	root 'welcome#index'
  	devise_for :users, controllers: { sessions: 'sessions', :registrations => 'registrations', :omniauth_callbacks => 'omniauth_callbacks' }  do
    	get 'logout' => 'devise/sessions#destroy'
	end
	match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup


	get '/about' => 'misc#about'
	get '/why' => 'misc#why'
	get '/terms-condition' => 'misc#terms-condition'
	get '/pledge-now' => 'misc#pledge_now'
	get '/how' => 'misc#how'
	match '/feedback' => 'misc#feedback', via: [:get, :post]
	get '/disclaimer' => 'misc#disclaimer'
	get '/terms-and-conditions' => 'misc#terms_and_conditions'

	get '/api/find_children' => 'api#find_children'
	post '/payment' => 'api#payment'
	post '/valid-refid' => 'api#valid_refid'
	post '/shared-contributions/:id/' => 'api#payment'

	get '/update-profile' => 'users#update_profile'

	post '/payu/ok' => 'payu#ok'
	post '/payu/error' => 'payu#error'
	post '/payu/report' => 'payu#report'

	post '/profile-update' => 'users#profile_update'
	get '/member-associate' => 'users#member_associate'
	match '/save-profile' => 'users#save_profile', via: [:patch, :post]
	post '/save-child' => 'users#save_child'

	get '/buddy-referrals' => 'users#buddy_referrals'
	get '/registered-children' => 'users#registered_children'
	post '/invite-referral' => 'users#invite_referral'
	match '/change-password' => 'users#change_password', via: [:get, :post]

	post 'payment/checkout'
  	get 'payment/:id/cancle' => 'payment#cancle'
	get 'payment/:id/success' => 'payment#success'
	post 'payment/:id/ipn_notify' => 'payment#ipn_notify'

end

app/controllers/misc_controller.rb
class MiscController < ApplicationController

	def pledge_now
		if !user_signed_in?
    		users = User.all_children.order("RANDOM()").limit(12)#.page(params[:page]).per(5)
    		@children = users.map { |children| {:id => children.id, :first_nm => children.first_nm, :last_nm => children.last_nm, :ref_id => children.ref_id, profile: "#{children.avatar.url rescue  '/assets/photo_not_found.png' }", email: children.email} }
    		render "/misc/children.html.erb"
    	else
			@user = User.new
			@user.guardians.new
			@user.guardians.new
			@cups = Cup.all
			@child = User.find_by_ref_id(params[:ref_id]) unless params[:ref_id].nil?
			@frequencies = Frequency.all
    	end
	end

	def feedback
		if request.post?
			@feedback = Feedback.new(params.require(:feedback).permit(:email, :message, :phone, :subject))
			if @feedback.save
				UsersMailer.feedback(params[:feedback]).deliver
				flash.now[:success] = "Your feedback has been sent successfully!"
				@feedback = Feedback.new
			else
				flash.now[:error] = @feedback.errors.full_messages.join(", ")
			end
		else
			@feedback = Feedback.new
		end
	end
end

app/helpers/misc_helper.rb
module MiscHelper

	# Generate dummy transaction id for session
	def dummy_transaction_id user_id, child_id
		"MUL#{user_id}#{child_id}#{Time.now.to_i}"
	end
end

app/views/misc/_coffee_contribution.html.erb
<div class="cart">
  <div class="c1 col-xs-12">
    <div class="hd1" style="width: 100%; border-radius: 3px;">
      <i class='fa fa-bars'></i> Coffee Contribution
    </div>
  </div>
  <ul>
    <% @cups.each do |cup| %>
      <li class="cart-item">
        <span class="cart-item-pic">
          <img src="<%= cup.image %>">
        </span>
        $1.49
        <span class="cart-item-desc"><%= cup.name %></span>
        <span class="cart-item-price"><input type="text" placeholder="howmany..." class="txtOnlyNumber howmanyCups" name="howmanyCups[]"></span>
      </li>
    <% end %>
  </ul>
  <div class="cart-bottom">
    Total: <input type="text" id="total_contributions" name='total_contributions' placeholder="Total" class="txtOnlyNumber">
    <a href="#" class="cart-button">Continue</a>
  </div>
</div>

app/views/misc/_profile_item.html.erb
<div class="box" data-ref-id="<%= child[:ref_id] %>">
	<div data-thumbnail="<%= child[:profile] %>"></div>
    
    <div data-image="<%= child[:profile] %>"></div>
    
    <div class="thumbnail-caption">
        <h3><%= "#{child[:first_nm].try(:titlecase)} #{child[:last_nm].try(:titlecase)}" %></h3>
        <h5><%= child[:ref_id] %></h5>
    </div>

    <div class="lightbox-text">
        <%= "#{child[:first_nm].try(:titlecase)} #{child[:last_nm].try(:titlecase)}" %> | <%= child[:email] %> | <%= child[:ref_id] %>
    </div>
</div>

app/views/misc/about.html.erb
<%= content_tag( "div", class: "container" ) do %>
	<div class="mg10">
		<div class="c1 col-xs-12">
		    <div class="hd1">
			    <i class='fa fa-bars'></i> Vision
			</div>
			<div class="content pd10"> Help children to establish College fund </div>
		</div>
		<div class="c1 col-xs-12">
			<div class="hd1">
			    <i class='fa fa-bars'></i> Mission
			</div>
			<div class="content pd10">Provide non Profit Organization, the means to empower their youth with an educational funding that would inspire kids throughout their development because the college coffee cup (CCC) Can be started as early as ONE day old, it would give young mother the hope	and inspiration needed for the success of both Mother and Child.
			</div>
		</div>
	</div>	
<% end %>

app/views/misc/become_member.html.erb
<div class="container white-font">
	<div class="mg10 thmcolor pd30">
		<h2>Become a Member/ Associate:</h2>
			<span class="fnt18">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span>
	</div>
</div>

app/views/misc/children.html.erb
<div class="container white-font pd10 thmcolor">
	<div id="grid">
		<% @children.each do |child| %>
			<%= render "profile_item", child: child %>
		<% end %>
	</div>
</div>

app/views/misc/disclaimer.html.erb
<div class="container white-font">
	<div class="mg10 thmcolor pd30">
		<h2 class="pcenter">Disclaimer</h2>
		<span class="fnt16">
		<p align="justify">
		The Gail A. Hall College Coffee Club is a rewards points program and 100% of the proceeds belong to The College Coffee Club. 6% of each pledge is paid to United Sponsors of America for web site services. There is a 49 cent transaction fee assessed to each donation of which 6 cents is retain by USA Educational Support Services for marketing and distribution. Many Useful Lives Cultivated Here ( MULCH ) and United Sponsors of America are works in progress and are not officially open to the public. It is estimated that site will officially open on or about January 1, 2015.At this time initial proceeds may be used as seed money for the start up cost of the Gail A. Hall College Coffee Club web site including any and all applicable fees necessary to comply with State, Federal, and International laws.
		</p>
		</span>
	</div>
</div>

app/views/misc/feedback.html.erb
<div class="container" style="margin-bottom: 20px;">
      <div class="mg10 pd30">
      
      <%= render partial: '/shared/flash_messages', collection: [:notice, :alert, :success, :error], as: :level %>
      
      <%= form_for @feedback, :url => feedback_path, method: :post do |f| %>
            <div class="c1 col-xs-12">
            	<div class="hd1">
            	    <i class='fa fa-bars'></i> Feedback
            	</div>
            	<div class="content">
                        <%= content_tag( "div", class: "form-group" ) do %>
                        	<%= f.label "Subject", class: "col-sm-2 control-label", for: 'feedback_subject' %>
                        	<%= content_tag( "div", class: "col-sm-10" ) do %>
            			   <%= f.text_field :subject, class: "form-control", autofocus: true, placeholder: 'Subject' %>
                  		<% end %>
                        <% end %>
            	      <%= content_tag( "div", class: "form-group" ) do %>
                        	<%= f.label "Email *", class: "col-sm-2 control-label", for: 'feedback_email' %>
                        	<%= content_tag( "div", class: "col-sm-10" ) do %>
            			   <%= f.email_field :email, class: "form-control", autocomplete: "off", placeholder: 'Email *', required: true %>
                  		<% end %>
                        <% end %>
                        <%= content_tag( "div", class: "form-group" ) do %>
                        	<%= f.label "Phone", class: "col-sm-2 control-label", for: 'feedback_phone' %>
                        	<%= content_tag( "div", class: "col-sm-10" ) do %>
            			   <%= f.text_field :phone, class: "form-control", autocomplete: "off", placeholder: 'Phone' %>
                  		<% end %>
                        <% end %>
                        <%= content_tag( "div", class: "form-group" ) do %>
                              <%= f.label "Message *", class: "col-sm-2 control-label", for: 'feedback_message' %>
                              <%= content_tag( "div", class: "col-sm-10" ) do %>
                                 <%= f.text_area :message, class: "form-control", placeholder: 'Type your message here...', required: true %>
                              <% end %>
                        <% end %>
                  </div>
            </div>
            <%= content_tag( "div", class: "form-group") do %>
                  <%= content_tag( "div", class: "col-sm-8" ) do %>
                        <%= f.submit "Send", class: 'col-sm-5 btn btn-primary pull-right' %>
                  <% end %>
            <% end %>
      <% end %>
      </div>
</div>

app/views/misc/pledge_now.html.erb
<div class="container white-font" style="margin-bottom: 20px;">
	<div class="mg10 pd30">
		<ul class="nav nav-tabs" role="tablist">
			<li class="active"><a href="#pledge-now" role="tab" data-toggle="tab">Pledge Now</a></li>
			<li><a href="#register-child" role="tab" data-toggle="tab">Enroll Toddler</a></li>
		</ul>

		<div class="tab-content pd10">
			<div class="tab-pane fade in active" id="pledge-now">
				<div class="row">
					<div class="col-xs-2">
						<ol class="scroll-nav">
							<li class="c1 others">Choose Child</li>
							<li class="c2 others">Donate</li>
							<li class="c3 others">Payment</li>
						</ol>
					</div>
					<div class="col-xs-10">
						<!-- <form role="form" method="post" id='pledgeNowForm' action="/payment" data-remote='true' onsubmit="payment_loader()"> -->
						<form role="form" method="post" id='pledgeNowForm' action="/payment/checkout">
							<div id="c1" class="form-group">
								<div class="col-xs-12">
                                    <div class="c1 col-xs-12">
                                        <div class="hd1" style="width: 100%; border-radius: 3px;">
		        					        <i class='fa fa-bars'></i> Choose Child
				        		        </div>
                                    </div>
                                
									<input type="search" class="form-control search" id="search" placeholder="Search by First Name / Last Name / Ref ID ..." autocomplete="off" autofocus='true'>
									<!-- <input type="button" value="Search Child" id="search_children"> -->
									<div id="searched_children" class="pcenter">
									</div>
								</div>
							</div>
							<div id="c2" style="display:none;">
								<div class="c1 col-xs-12">
								    <div class="hd1" style="width: 100%; border-radius: 3px;">
								    	<i class='fa fa-bars'></i> Coffee Contribution
								    </div>
							  	</div>
								<table class="table">
									<tbody>
										<% @cups.each_with_index do |cup, index| %>
										<tr valign="center">
											<td><div class="checkbox">
														<label><input type="checkbox" id="cup_<%=index%>" class="contribution_cups" name='coffee_cups[]' data-price='<%= cup.price %>' value="<%= cup.id %>">
													<%= cup.name %>
													</label>
												</div>
											<td><img src="<%= cup.image %>" width="50px" height="50px">
											<td><input type="text" placeholder="howmany..." class="txtOnlyNumber howmanyCups" name="howmanyCups[]">
										</tr>
										<% end %>
										<tr valign="center">
											<td></td>
											<td><h4>Total</h4>
											<td><input type="text" id="total_contributions" name='total_contributions' placeholder="Total" class="txtOnlyNumber"> 
										</tr>
									</tbody>
								</table>
								<div class="c1 col-xs-12">
								    <div class="hd1" style="width: 100%; border-radius: 3px;">
								    	<i class='fa fa-bars'></i> Frequency
								    </div>
							  	</div>
								<table class="table">
									<tbody>
										<tr valign="center">
											<% @frequencies.each_with_index do |f, index| %>
												<td><div class="radio">
														<input type="radio" name='freq' class="freq css-radio" id="freq_<%=index%>" value="<%= f.alias %>"> 													
														<label for="freq_<%=index%>" class="css-label-radio"><%= f.name %></label>
                                                        </div>
												</td>
											<% end %>
										</tr>
										<tr valign="center">
											<td colspan="5"> <center><input type="button" onclick='c3();' class="btn btn-primary" value='CONTINUE >>>'></center></td>
										</tr>
									</tbody>
								</table>
							</div>
							<div id="c3" style="display:none;">
                                <div class="c1 col-xs-12">
								    <div class="hd1" style="width: 100%; border-radius: 3px;">
								    	<i class='fa fa-bars'></i> Payment
								    </div>
							  	</div>

								<table class="table">
									<tbody>
										<tr valign="center">
											<td valign="center"><%= image_tag '', class: 'chld', size: '75x75' %></td>
											<td valign="center">
												<address>
													<strong>Dummy Dummy.</strong><br>
												  	abc@gmail.com<br>
												  	3ADSF45<br>
												</address></td>
											<td></td>
										</tr>
										<tr valign="center">
											<td valign="center">Total Coffee Contribution</td>
											<td valign="center"><span class='l_total_contributions'>  </span>
											<td></td>
										</tr>
										<tr valign="center">
											<td valign="center">Frequency</td>
											<td valign="center"><label id='l_freq'>  </label>
											<td></td>
										</tr>
									</tbody>
								</table>

								<div class="c1 col-xs-12">
								    <div class="hd1" style="width: 100%; border-radius: 3px;">
								    	<i class='fa fa-bars'></i> Choose payment method from following
								    </div>
							  	</div>
								
								<table class="table">
									<tbody>
										<tr valign="center">
											<%= hidden_field_tag :payment_type, '' %>
											<td></td>
											<td><h5>Payment Using <br>Credit Card / Debit Card</h5></td>
											<td><h5>Pay In Person</h5></td>
										</tr>
										<tr valign="center">
											<td>Total Coffee Contribution</td>
											<td><span class="l_total_contributions"></span>
											<td><span class="l_total_contributions"></span>
										</tr>
										<tr valign="center">
											<td>Transaction Fee</td>
											<td>$ 0.49</td>
											<td>$ 0.49</td>
										</tr>
										<tr valign="center">
											<td>Service Fee (2.9%)</td>
											<td>$ <span class="service_fee"></span></td>
											<td>$ 0.00</td>
										</tr>
										<tr valign="center">
											<td>Total Amount</td>
											<td><b>$ <span id="total_fee"></span></b></td>
											<td><b><span id="total_fee_pay_in_person"></span></b></td>
										</tr>
										<tr valign="center">
											<td></td>
											<td><img src='/assets/payment/paypal.jpg'></td>
											<td><img src='/assets/payment/pay1.jpg'></td>
										</tr>
										<tr valign="center">
											<td></td>
											<td><a href="javascript:submit_contribution('paypal');" class="btn btn-primary">Choose</a></td>
											<td><a href="javascript:submit_contribution('pay_in_person');" data-method='post' onclick='payment_loader();' class="btn btn-primary">Choose</a></td>
										</tr>
									</tbody>
								</table>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="tab-pane fade" id="register-child">
				<span class='flash_messages'></span>
				<%= form_for @user, :url => save_child_path, html: { onsubmit: "if($('.new_user').valid() && ssn_unmasking()){show_loader('.flash_messages', '.loader')}" }, method: :post, remote: true, multipart: true do |f| %>
					<div class="c1 col-xs-12">
						<div class="hd1">
							<i class='fa fa-bars'></i> Personal Informatio
						</div>
						<div class="content">
							<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
							<%= f.hidden_field :parent_id, value: current_user.id %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						      <%= f.label "Full Name", class: "col-sm-2 control-label", for: 'user_first_nm' %>
						      <%= content_tag( "div", class: "col-sm-5" ) do %>
						        <%= f.text_field :first_nm, autofocus: true, class: "txtOnlyAlpha form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'First Name' %>
						      <% end %>
						    <% end %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						      <%= content_tag( "div", class: "col-sm-5" ) do %>
						        <%= f.text_field :last_nm, class: "txtOnlyAlpha form-control", autocomplete: "off", oninput: 'check_names(this)', placeholder: 'Last Name' %>
						      <% end %>
						    <% end %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						        <%= f.label "DOB", class: 'col-sm-2 control-label pull-left', for: 'user_dob' %>
						        <%= content_tag( "div", class: "col-sm-5 pull-right" ) do %>        
						          <%= f.text_field :dob, value: (@user.dob.nil? ? '' : @user.dob.strftime('%m/%d/%Y')), class: "datepicker form-control", placeholder: "MM/DD/YYYY", onchange: 'age_calculate()', readonly: true %>
						        <% end %>
					      	<% end %>

					      	<%= content_tag( "div", class: "form-group" ) do %>
						        <%= content_tag( "div", class: "col-sm-5" ) do %>
						          <%= f.text_field :role, class: "form-control", placeholder: "Role", disabled: true %>
						        <% end %>
					      	<% end %>

						    <%= content_tag( "div", class: "form-group user_role", style: 'display:none;' ) do %>
						        <%= f.label " ", class: 'col-sm-2 control-label', for: 'user_' %>
						        <%= content_tag( "div", class: "col-sm-10" ) do %>
						          <%= f.label "Student has to utilize the amount within 7 years, else the amount would be moved to Non-Profit Organization account", class: "form-control info" %>
						        <% end %>
						    <% end %>

						    <%= content_tag( "div", class: "form-group user_role" ) do %>
						        <%= f.label "Email *", class: 'col-sm-2 control-label', for: 'user_email' %>
						        <%= content_tag( "div", class: "col-sm-10" ) do %>
						          <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
						        <% end %>
						    <% end %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						      	<%= f.label "Gender", class: 'col-sm-2 control-label', for: 'user_gender' %>
						    	<%= content_tag( "div", class: "col-sm-10 radio fnt18", style: "margin-top: 5px;" ) do %>
							        <input type="radio" name="user[gender]" id="gender_male" class="user_gender css-radio" value="male" <%= "checked" if @user[:gender]=="male" %>>
							        <label class="col-sm-2 css-label-radio" for="gender_male">Male</label>

							        <input type="radio" name="user[gender]" id="gender_female" class="user_gender css-radio" value="female" <%= "checked" if @user[:gender]=="female" %>>
							        <label class="col-sm-2 css-label-radio" for="gender_female">Female</label>
							        
							        <label id="user_phone-error" class="col-sm-6 error hidden" for="user_phone"></label>
							    <% end %>
						    <% end %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						        <%= f.label "Phone", class: 'col-sm-2 control-label', for: 'user_phone' %>
						        <%= content_tag( "div", class: "col-sm-5" ) do %>
						          <%= f.text_field :phone, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Home Phone" %>
						        <% end %>
					      	<% end %>

					      	<%= content_tag( "div", class: "form-group" ) do %>
						        <%= content_tag( "div", class: "col-sm-5" ) do %>
						          <%= f.text_field :mobile, autocomplete: "off", class: "txtOnlyNumber form-control", placeholder: "Mobile *" %>
						        <% end %>
					      	<% end %>

					      	<%= content_tag( "div", class: "form-group" ) do %>
						        <%= f.label "Profile Picture *", class: 'col-sm-2 control-label', for: 'user_profile' %>
						        <%= content_tag( "div", class: "col-sm-5" ) do %>
						          <div class="browse col-sm-8" onclick="image_via_file(this);"> <i class='fa fa-image'></i> &nbsp &nbsp Browse</div>
						          <img src="<%= @user.avatar.url %>" id="img-preview" class="pull-right" width="50px" height="50px">
						          <%= f.file_field :avatar, class: "choose-file form-control", pattern: ".jpg, .png" %>
						        <% end %>
					    	<% end %>

						    <%= content_tag( "div", class: "form-group" ) do %>
						        <%= content_tag( "div", class: "col-sm-5" ) do %>
						        	<%= f.hidden_field :ssn, value: @user.ssn %>
		          					<input class="form-control txtOnlyNumber valid" id="ssn" placeholder="SSN - Social Security No" data-value='<%= @user.ssn %>' type="text" aria-invalid="false">
						        <% end %>
						    <% end %>
						</div>
					</div>

				    <%= f.fields_for :guardians do |ff| %>
	        			<%= render '/shared/update_profile_guardians', ff: ff, index: @user.guardians.index(ff.object) if @user.guardians.index(ff.object) <= 1 %>
	  				<% end %>

	  				<%= content_tag( "div", class: "loader form-group", style: "display:none;" ) do %>
				        <%= content_tag( "div", class: "col-sm-5" ) do %>
	  						<img src="/assets/ajax-loader.gif"> Please wait..
	  					<% end %>
	  				<% end %>

	  				<%= content_tag( "div", class: "form-group") do %>
					    <%= content_tag( "div", class: "col-sm-8" ) do %>
					        <%= f.submit "Enroll Toddler", class: 'col-sm-5 btn btn-primary pull-right' %>
					        <% if @is_new_user %>
					          <span class="col-sm-5 btn btn-default pull-right" onclick="$('#updateProfile').modal('hide');">Skip</span>
					        <% end %>
						<% end %>
				    <% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function(){
		<% unless params[:ref_id].nil? %>
			letsSearch("<%= @child.first_nm %>");
		<% end %>		
	});
</script>

app/views/misc/terms-condition.html.erb
<div class="container white-font">
	<div class="mg10 thmcolor pd30">
		<h2>Terms and Conditions:</h2>
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
	</div>
</div>

app/views/misc/under-const.html.erb
<div class="container white-font">
	<div class="mg10 thmcolor pd30">
		<h1 class="pcenter under-construct"><span class='pd20'>Under Construction !!</span></h1>
		<h3 class="pcenter under-construct"><span class='pd20'>We are so thankful for your patience :)</span></h3>
		<div class="dualgear">
			<span class='gearOuter'></span>
			<span class='gearInner'></span>
		</div>			
	</div>
</div>

app/views/misc/why.html.erb
<%= content_tag( "div", class: "container" ) do %>
	<div class="mg10">
		<div class="c1 col-xs-12">
		    <div class="hd1">
			    <i class='fa fa-bars'></i> Objectives
			</div>
			<div class="content pd10"> 
				<ul>
					<li>Provide non profits with gain donations, helping establish and develop educational funds for youth </li>
					<li>Encourage every youth to continue their education after High School and provide cash incentives for Graduates </li>
					<li>Allow and encourage Higher Studies Juniors to participate in a foreign student exchange program </li>
				</ul>
			</div>
		</div>
	</div>
<% end %>